# Generated by Django 5.0.4 on 2024-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
